"""empty message

Revision ID: 84953951dc1c
Revises: 68f653083f81
Create Date: 2020-04-13 05:02:24.990351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84953951dc1c'
down_revision = '68f653083f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
